---
app:
  persistence:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://localhost:3307/app?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
  kafka:
    input-topic-name: input-data
    create-topics: false
  data:
    path:
    initial: false

# Spring configuration
spring:
  batch:
    initialize-schema: never
  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers:
      - localhost:29092
